menu:
    Blog: /
    Archive: /archives/
    Zhihu: https://www.zhihu.com/people/ai-xin-jue-luo-nu-er-ha-chi/activities
    GitHub: https://github.com/SeasideLee

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
